name: Docker Image CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  
jobs:
  builds:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with PECL extension
        run: |  
          sudo apt-get install -y nginx software-properties-common

          
      
